name: CD - Deploy Angular dist on S3

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        type: choice
        options:
          - 'DEV'
          - 'PROD'
        required: true
        default: 'DEV'
  push:
    branches:
      - master

jobs:
    build-and-test:
      uses: ./.github/workflows/ci-workflow-frontend.yaml
      secrets: inherit

    deploy:
      needs: build-and-test
      runs-on: ubuntu-latest
      environment: ${{ inputs.environment || 'DEV' }}
      steps:
      - name: Set ENVIRONMENT fallback
        run: |
          echo "DEPLOY_ENV=${{ inputs.environment != '' && inputs.environment || vars.ENVIRONMENT || 'DEV' }}" >> $GITHUB_ENV

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ vars.APP_NAME }}
          path: dist/${{ vars.APP_NAME }}

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ vars.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SOURCE_DIR: dist/${{ vars.APP_NAME }}
